// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-songs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function requiredEnv(name) {
  const value = runtimeEnv(name)?.trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
}
function supabaseAdmin() {
  return createClient(requiredEnv("SUPABASE_URL"), requiredEnv("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAuth(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Missing bearer token");
  const { data, error } = await supabaseAdmin().from("site_settings").select("value").eq("key", "mcp_api_token").maybeSingle();
  if (error) throw new Error("Auth lookup failed: " + error.message);
  const configured = typeof data?.value === "string" ? data.value : data?.value?.token;
  if (!configured || configured !== token) throw new Error("Invalid MCP API token");
}

// src/lib/mcp/tools/list-songs.ts
var toSongJson = (s) => ({
  id: s.id,
  title: s.title,
  artist: s.artist,
  genre: s.genre,
  mood: s.mood,
  duration: s.duration,
  file_url: s.file_url,
  cover_url: s.cover_url,
  bpm: s.bpm,
  key_scale: s.key_scale,
  time_signature: s.time_signature,
  quality_score: s.quality_score,
  prompt: s.prompt,
  lyrics: s.lyrics,
  origin_source: s.origin_source,
  created_at: s.created_at,
  deleted_at: s.deleted_at
});
var list_songs_default = defineTool({
  name: "list_songs",
  title: "List songs",
  description: "List songs in the library with optional search and filters.",
  inputSchema: {
    search: z.string().optional().describe("Match title or artist (case-insensitive)."),
    genre: z.string().optional(),
    mood: z.string().optional(),
    include_trash: z.boolean().optional().describe("Include soft-deleted songs."),
    limit: z.number().int().min(1).max(500).optional(),
    offset: z.number().int().min(0).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, genre, mood, include_trash, limit = 100, offset = 0 }, ctx) => {
    await requireAuth(ctx);
    let q = supabaseAdmin().from("songs").select("*").order("created_at", { ascending: false }).range(offset, offset + limit - 1);
    if (!include_trash) q = q.is("deleted_at", null);
    if (search) q = q.or(`title.ilike.%${search}%,artist.ilike.%${search}%`);
    if (genre) q = q.eq("genre", genre);
    if (mood) q = q.eq("mood", mood);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const songs = (data ?? []).map((s) => toSongJson(s));
    return { content: [{ type: "text", text: JSON.stringify(songs) }], structuredContent: { songs } };
  }
});

// src/lib/mcp/tools/get-song.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_song_default = defineTool2({
  name: "get_song",
  title: "Get song",
  description: "Get full details for one song, including prompt, lyrics and quality metadata.",
  inputSchema: { id: z2.string().uuid().describe("Song ID.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    await requireAuth(ctx);
    const { data, error } = await supabaseAdmin().from("songs").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Song not found" }], isError: true };
    const s = data;
    const song = { id: s.id, title: s.title, artist: s.artist, genre: s.genre, mood: s.mood, duration: s.duration, file_url: s.file_url, cover_url: s.cover_url, bpm: s.bpm, key_scale: s.key_scale, time_signature: s.time_signature, quality_score: s.quality_score, prompt: s.prompt, lyrics: s.lyrics, origin_source: s.origin_source, created_at: s.created_at, deleted_at: s.deleted_at };
    return { content: [{ type: "text", text: JSON.stringify(song) }], structuredContent: { song } };
  }
});

// src/lib/mcp/tools/update-song.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var update_song_default = defineTool3({
  name: "update_song",
  title: "Update song metadata",
  description: "Edit a song's title, artist, genre, mood, prompt, lyrics, BPM, key, time signature or cover URL.",
  inputSchema: {
    id: z3.string().uuid(),
    title: z3.string().min(1).optional(),
    artist: z3.string().min(1).optional(),
    genre: z3.string().nullable().optional(),
    mood: z3.string().nullable().optional(),
    prompt: z3.string().nullable().optional(),
    lyrics: z3.string().nullable().optional(),
    bpm: z3.number().int().nullable().optional(),
    key_scale: z3.string().nullable().optional(),
    time_signature: z3.string().nullable().optional(),
    cover_url: z3.string().url().nullable().optional(),
    quality_score: z3.number().min(0).max(100).nullable().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...updates }, ctx) => {
    await requireAuth(ctx);
    const clean = Object.fromEntries(Object.entries(updates).filter(([, v]) => v !== void 0));
    if (Object.keys(clean).length === 0) {
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    }
    const { data, error } = await supabaseAdmin().from("songs").update(clean).eq("id", id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Song not found" }], isError: true };
    const s = data;
    const song = { id: s.id, title: s.title, artist: s.artist, genre: s.genre, mood: s.mood, prompt: s.prompt, lyrics: s.lyrics, bpm: s.bpm, key_scale: s.key_scale, time_signature: s.time_signature, cover_url: s.cover_url, quality_score: s.quality_score };
    return { content: [{ type: "text", text: `Updated song ${id}` }], structuredContent: { song } };
  }
});

// src/lib/mcp/tools/delete-song.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var delete_song_default = defineTool4({
  name: "delete_song",
  title: "Delete song (trash)",
  description: "Soft-delete a song. It stays in trash for 30 days and can be restored.",
  inputSchema: { id: z4.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    await requireAuth(ctx);
    const { error } = await supabaseAdmin().from("songs").update({ deleted_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Song ${id} moved to trash` }] };
  }
});

// src/lib/mcp/tools/restore-song.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var restore_song_default = defineTool5({
  name: "restore_song",
  title: "Restore song",
  description: "Restore a soft-deleted song from trash back into the library.",
  inputSchema: { id: z5.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    await requireAuth(ctx);
    const { error } = await supabaseAdmin().from("songs").update({ deleted_at: null }).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Song ${id} restored` }] };
  }
});

// src/lib/mcp/tools/list-playlists.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_playlists_default = defineTool6({
  name: "list_playlists",
  title: "List playlists",
  description: "List all playlists with song counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    await requireAuth(ctx);
    const db = supabaseAdmin();
    const { data: playlists, error } = await db.from("playlists").select("*").order("title");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: ps } = await db.from("playlist_songs").select("playlist_id");
    const counts = {};
    ps?.forEach((r) => {
      counts[r.playlist_id] = (counts[r.playlist_id] || 0) + 1;
    });
    const result = (playlists ?? []).map((p) => ({
      id: p.id,
      title: p.title,
      description: p.description,
      cover_image_url: p.cover_image_url,
      song_count: counts[p.id] ?? 0,
      created_at: p.created_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: { playlists: result } };
  }
});

// src/lib/mcp/tools/get-playlist-songs.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z6 } from "npm:zod@^3.25.76";
var get_playlist_songs_default = defineTool7({
  name: "get_playlist_songs",
  title: "Get playlist songs",
  description: "List the songs in a playlist, in order.",
  inputSchema: { playlist_id: z6.string().uuid() },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ playlist_id }, ctx) => {
    await requireAuth(ctx);
    const db = supabaseAdmin();
    const { data: links, error } = await db.from("playlist_songs").select("song_id, position").eq("playlist_id", playlist_id).order("position");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (links ?? []).map((l) => l.song_id);
    if (ids.length === 0) return { content: [{ type: "text", text: "[]" }], structuredContent: { songs: [] } };
    const { data: songs, error: sErr } = await db.from("songs").select("*").in("id", ids);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const byId = new Map((songs ?? []).map((s) => [s.id, s]));
    const ordered = (links ?? []).flatMap((l) => {
      const s = byId.get(l.song_id);
      return s ? [{ position: l.position, id: s.id, title: s.title, artist: s.artist, genre: s.genre, mood: s.mood, duration: s.duration }] : [];
    });
    return { content: [{ type: "text", text: JSON.stringify(ordered) }], structuredContent: { songs: ordered } };
  }
});

// src/lib/mcp/tools/create-playlist.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z7 } from "npm:zod@^3.25.76";
var create_playlist_default = defineTool8({
  name: "create_playlist",
  title: "Create playlist",
  description: "Create a new playlist.",
  inputSchema: {
    title: z7.string().min(1),
    description: z7.string().optional(),
    cover_image_url: z7.string().url().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ title, description, cover_image_url }, ctx) => {
    await requireAuth(ctx);
    const { data, error } = await supabaseAdmin().from("playlists").insert({ title, description: description ?? null, cover_image_url: cover_image_url ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const p = data;
    const playlist = { id: p.id, title: p.title, description: p.description, cover_image_url: p.cover_image_url, created_at: p.created_at };
    return { content: [{ type: "text", text: `Created playlist "${title}"` }], structuredContent: { playlist } };
  }
});

// src/lib/mcp/tools/update-playlist.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z8 } from "npm:zod@^3.25.76";
var update_playlist_default = defineTool9({
  name: "update_playlist",
  title: "Update playlist",
  description: "Rename a playlist or change its description or cover.",
  inputSchema: {
    id: z8.string().uuid(),
    title: z8.string().min(1).optional(),
    description: z8.string().nullable().optional(),
    cover_image_url: z8.string().url().nullable().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...updates }, ctx) => {
    await requireAuth(ctx);
    const clean = Object.fromEntries(Object.entries(updates).filter(([, v]) => v !== void 0));
    if (Object.keys(clean).length === 0) return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    const { error } = await supabaseAdmin().from("playlists").update(clean).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Playlist ${id} updated` }] };
  }
});

// src/lib/mcp/tools/delete-playlist.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z9 } from "npm:zod@^3.25.76";
var delete_playlist_default = defineTool10({
  name: "delete_playlist",
  title: "Delete playlist",
  description: "Delete a playlist and its song links. Songs themselves are kept in the library.",
  inputSchema: { id: z9.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    await requireAuth(ctx);
    const db = supabaseAdmin();
    await db.from("playlist_songs").delete().eq("playlist_id", id);
    const { error } = await db.from("playlists").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Playlist ${id} deleted` }] };
  }
});

// src/lib/mcp/tools/add-song-to-playlist.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z10 } from "npm:zod@^3.25.76";
var add_song_to_playlist_default = defineTool11({
  name: "add_song_to_playlist",
  title: "Add song to playlist",
  description: "Add a song to the end of a playlist.",
  inputSchema: {
    playlist_id: z10.string().uuid(),
    song_id: z10.string().uuid()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ playlist_id, song_id }, ctx) => {
    await requireAuth(ctx);
    const db = supabaseAdmin();
    const { data: existing } = await db.from("playlist_songs").select("id").eq("playlist_id", playlist_id).eq("song_id", song_id).maybeSingle();
    if (existing) return { content: [{ type: "text", text: "Song already in playlist" }], isError: true };
    const { data: maxPos } = await db.from("playlist_songs").select("position").eq("playlist_id", playlist_id).order("position", { ascending: false }).limit(1).maybeSingle();
    const { error } = await db.from("playlist_songs").insert({ playlist_id, song_id, position: (maxPos?.position ?? -1) + 1 });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Song added to playlist" }] };
  }
});

// src/lib/mcp/tools/remove-song-from-playlist.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z11 } from "npm:zod@^3.25.76";
var remove_song_from_playlist_default = defineTool12({
  name: "remove_song_from_playlist",
  title: "Remove song from playlist",
  description: "Remove a song from a playlist. The song stays in the library.",
  inputSchema: {
    playlist_id: z11.string().uuid(),
    song_id: z11.string().uuid()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ playlist_id, song_id }, ctx) => {
    await requireAuth(ctx);
    const { error } = await supabaseAdmin().from("playlist_songs").delete().eq("playlist_id", playlist_id).eq("song_id", song_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Song removed from playlist" }] };
  }
});

// src/lib/mcp/tools/library-stats.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@3.0.4";
var library_stats_default = defineTool13({
  name: "library_stats",
  title: "Library stats",
  description: "Get totals: songs, trashed songs, playlists, and genre/mood distribution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    await requireAuth(ctx);
    const db = supabaseAdmin();
    const [{ count: total }, { count: trashed }, { count: playlists }, { data: songs }] = await Promise.all([
      db.from("songs").select("*", { count: "exact", head: true }).is("deleted_at", null),
      db.from("songs").select("*", { count: "exact", head: true }).not("deleted_at", "is", null),
      db.from("playlists").select("*", { count: "exact", head: true }),
      db.from("songs").select("genre, mood").is("deleted_at", null)
    ]);
    const genres = {};
    const moods = {};
    songs?.forEach((s) => {
      if (s.genre) genres[s.genre] = (genres[s.genre] || 0) + 1;
      if (s.mood) moods[s.mood] = (moods[s.mood] || 0) + 1;
    });
    const stats = { songs: total ?? 0, trashed: trashed ?? 0, playlists: playlists ?? 0, genres, moods };
    return { content: [{ type: "text", text: JSON.stringify(stats) }], structuredContent: { stats } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sound-space",
  title: "sound-space",
  version: "1.0.0",
  instructions: "Tools for the sound-space music library. Authenticate with the MCP API token as a bearer token. Use list_songs/get_song to browse the catalog, update_song to edit metadata (title, artist, genre, mood, prompt, lyrics, BPM, key), delete_song/restore_song for trash management, and the playlist tools to curate playlists.",
  tools: [
    list_songs_default,
    get_song_default,
    update_song_default,
    delete_song_default,
    restore_song_default,
    list_playlists_default,
    get_playlist_songs_default,
    create_playlist_default,
    update_playlist_default,
    delete_playlist_default,
    add_song_to_playlist_default,
    remove_song_from_playlist_default,
    library_stats_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
